theme:  jekyll-theme-cayman
title:  React Redux Webpack Starter Kit
description: "React Redux Webapack and eslint Starter Kit is which let's you build smart real world apps."
keywords: "React Redux Webpack Starter Kit, React, Redux, Starter Kit, Webpack, Babel, material-ui, Eslint, Smart kit, material, build, ReactJs, Beginner, react app example, react best practices, react app, react redux starter kit, react redux tutorial, react redux demo, material-ui react examples "
author: Nisarg R Thakkar
improve_content: https://github.com/nisargrthakkar/react-redux-starter-kit/issues
whitelist:
  - jekyll-sitemap
  - jekyll-seo-tag
  
google_author:  "https://plus.google.com/u/1/+NisargThakkar113"
og_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png"
og_locale:  "en_EN"
og_type:  "website"
og_title: "React Redux Webpack Starter Kit"
og_description: "React Redux Webapack and eslint Starter Kit is which let's you build smart real world apps."
twitter_image:  "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png"
twitter_locale: "en_EN"
twitter_type: "website"
twitter_title:  "React Redux Webpack Starter Kit"
twitter_description:  "React Redux Webapack and eslint Starter Kit is which let's you build smart real world apps."
